config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :people

  root "people#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord

scope :ordered, -> { order(last_name: :asc) }
scope :filter_by_first_name, -> (first_name) { where('first_name like ?', "%#{first_name}%")}

  def full_name
    "#{first_name} #{last_name} " 
  end

  def self.search(term)
    where(["(`people`.`first_name` LIKE :term OR
      `people`.`last_name` LIKE :term OR
      `people`.`birth_date` LIKE :term OR
      `people`.`death_date` LIKE :term)", { term: "%#{term}%" }])
  end
end

app/models/place.rb
class Place < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all.ordered
    
    if params[:search]
      @people = Person.search(params[:search]).ordered unless params[:search].blank?
    else
      @people = Person.all.ordered
    end
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.permit(:search)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show edit update destroy ]

  # GET /places or /places.json
  def index
    @places = Place.all
  end

  # GET /places/1 or /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to place_url(@place), notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to place_url(@place), notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.fetch(:place, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FamilyTree
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/people/_form.html.haml
= form_with(model: person) do |form|
  - if person.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(person.errors.count, "error")
        prohibited this person from being saved:
      %ul
        - person.errors.each do |error|
          %li= error.full_message
  %div
    = form.submit

app/views/people/_person.html.haml
%div{:id => "#{dom_id person}"}

app/views/people/edit.html.haml
%h1 Editing person
= render "form", person: @person
%br/
%div
  = link_to "Show this person", @person
  |
  \#{link_to "Back to people", people_path}

app/views/people/index.html.haml
%p{:style => "color: green"}= notice
%h1 People
= form_tag "/people", method: "GET" do
  = label_tag :people
  = text_field_tag(:search, h(params[:search]), { placeholder: 'Search...' })
  = submit_tag "Search"
#people
  - @people.each do |person|
    = render person
    %p
      = link_to person.full_name, person
= link_to "New person", new_person_path

app/views/people/new.html.haml
%h1 New person
= render "form", person: @person
%br/
%div
  = link_to "Back to people", people_path

app/views/people/show.html.haml
%p{:style => "color: green"}= notice
= render @person
%div
  %h2
    = @person.full_name
  %p 
    Birth Date:
    = @person.birth_date
  %p
    Death Date:
    = @person.death_date
  %p
    Gender:
    = @person.gender
  = link_to "Edit this person", edit_person_path(@person)
  |
  \#{link_to "Back to people", people_path}
  
  \#{button_to "Destroy this person", @person, method: :delete}

app/views/places/_form.html.haml
= form_for @place do |f|
  - if @place.errors.any?
    #error_explanation
      %h2= "#{pluralize(@place.errors.count, "error")} prohibited this place from being saved:"
      %ul
        - @place.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/places/edit.html.haml
%h1 Editing place

= render 'form'

= link_to 'Show', @place
\|
= link_to 'Back', places_path

app/views/places/index.html.haml
%h1 Listing places

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @places.each do |place|
      %tr
        %td= link_to 'Show', place
        %td= link_to 'Edit', edit_place_path(place)
        %td= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Place', new_place_path

app/views/places/new.html.haml
%h1 New place

= render 'form'

= link_to 'Back', places_path

app/views/places/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_place_path(@place)
\|
= link_to 'Back', places_path